---

- name: INSTALLING SOME PACKAGES
  apt: pkg={{ item }} state=latest
  become: yes
  with_items:
    - git
    - htop
    - nano
    - curl
    - zip
    - wget
    - make
    - openssh-server


- name: BE SURE NTP IS PRESENT
  apt: pkg=ntp state=present
  tags: ntp
  become: yes

- name: BE SURE NTP IS PRESENT AND STARTED
  service: name=ntp state=started enabled=yes
  tags: ntp
  become: yes
